name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build TS and Copy Resources
        run: npm run build

      - name: Inject Analytics Secrets
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
          GA_API_SECRET: ${{ secrets.GA_API_SECRET }}
        shell: bash
        run: |
          echo "{\"MEASUREMENT_ID\": \"$GA_MEASUREMENT_ID\", \"API_SECRET\": \"$GA_API_SECRET\"}" > dist/env.json

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          skip_build: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          max_attempts: 3
